// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";

let lovableAuth: ReturnType<typeof createLovableAuth>;
try {
  lovableAuth = createLovableAuth();
} catch {
  lovableAuth = { signInWithOAuth: async () => ({ error: new Error("Lovable auth unavailable") }) } as any;
}

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (
      provider: "google" | "apple" | "microsoft" | "lovable",
      opts?: SignInOptions,
    ) => {
      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens);
        // Backup em localStorage próprio para não ser apagado pelo auto-refresh
        try {
          localStorage.setItem("rotamais-auth-tokens", JSON.stringify(result.tokens));
        } catch {}
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
