// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    let token: string | undefined;

    try {
      const { data } = await supabase.auth.getSession();
      token = data.session?.access_token;

      // If token is expired, refresh before sending
      if (token) {
        const payload = JSON.parse(atob(token.split(".")[1]));
        if (payload?.exp && payload.exp * 1000 < Date.now()) {
          const refreshed = await supabase.auth.refreshSession();
          token = refreshed.data.session?.access_token;
        }
      }
    } catch {
      token = undefined;
    }

    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);
