// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { getSupabaseEnv } from "./env";

function decodeJwtPayload(token: string): Record<string, unknown> | null {
  try {
    return JSON.parse(atob(token.split(".")[1]));
  } catch {
    return null;
  }
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const { url, publishableKey } = getSupabaseEnv();

    if (!url || !publishableKey) {
      const missing = [
        ...(!url ? ["SUPABASE_URL"] : []),
        ...(!publishableKey ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    let userId: string | null = null;

    // First, try the standard Supabase getClaims verification
    const supabase = createClient<Database>(url, publishableKey, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data: claimsData, error: claimsError } = await supabase.auth.getClaims(token);
    if (claimsData?.claims?.sub) {
      userId = claimsData.claims.sub as string;
    }

    // Fallback: decode JWT locally and verify via admin client
    if (!userId) {
      const payload = decodeJwtPayload(token);
      if (!payload?.sub) {
        const msg = claimsError?.message ?? "Invalid token";
        throw new Error(`Unauthorized: ${msg}`);
      }

      const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
      const { data: userData, error: userError } = await supabaseAdmin.auth.getUser(token);
      if (userError || !userData?.user) {
        throw new Error("Unauthorized: Invalid token");
      }
      userId = userData.user.id;
    }

    return next({
      context: {
        supabase,
        userId,
        claims: { sub: userId },
      },
    });
  },
);
