// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { getSupabaseEnv } from "./env";

function createSupabaseAdminClient() {
  const { url, serviceRoleKey, publishableKey } = getSupabaseEnv();

  if (!url) {
    throw new Error("Missing Supabase environment variable(s): SUPABASE_URL. Connect Supabase in Lovable Cloud.");
  }

  const key = serviceRoleKey ?? publishableKey;
  if (!key) {
    throw new Error("Missing Supabase environment variable(s): SUPABASE_SERVICE_ROLE_KEY or SUPABASE_PUBLISHABLE_KEY. Connect Supabase in Lovable Cloud.");
  }

  return createClient<Database>(url, key, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
