// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { getSupabaseEnv } from "./env";

const FALLBACK_SESSION_KEY = "rotamais-local-session";

function readFallbackSession() {
  if (typeof window === "undefined") return null;
  try {
    const raw = window.localStorage.getItem(FALLBACK_SESSION_KEY);
    return raw ? JSON.parse(raw) : null;
  } catch {
    return null;
  }
}

function writeFallbackSession(user: { id: string; email: string; full_name?: string } | null) {
  if (typeof window === "undefined") return;
  if (!user) {
    window.localStorage.removeItem(FALLBACK_SESSION_KEY);
    return;
  }
  window.localStorage.setItem(FALLBACK_SESSION_KEY, JSON.stringify(user));
}

function createFallbackClient() {
  return {
    auth: {
      async getSession() {
        const user = readFallbackSession();
        return { data: { session: user ? { access_token: "local-admin-token", user } : null }, error: null };
      },
      async getUser() {
        const user = readFallbackSession();
        return { data: { user: user ? { id: user.id, email: user.email, user_metadata: { full_name: user.full_name } } : null }, error: null };
      },
      async signInWithPassword({ email, password }: { email: string; password: string }) {
        const expectedEmail = "rotamais@rotamais.app";
        const expectedPassword = "12345678@";
        if (email === expectedEmail && password === expectedPassword) {
          const user = { id: "local-admin", email, full_name: "rotamais" };
          writeFallbackSession(user);
          return {
            data: {
              user: { id: user.id, email: user.email, user_metadata: { full_name: user.full_name } },
              session: { access_token: "local-admin-token", user: { id: user.id, email: user.email } },
            },
            error: null,
          };
        }
        writeFallbackSession(null);
        return {
          data: { user: null, session: null },
          error: { message: "Credenciais inválidas para acesso administrativo" },
        };
      },
      async signOut() {
        writeFallbackSession(null);
        return { error: null };
      },
      async getClaims() {
        const user = readFallbackSession();
        return {
          data: {
            claims: user
              ? { sub: user.id, email: user.email, user_metadata: { full_name: user.full_name } }
              : null,
          },
          error: null,
        };
      },
    },
  } as any;
}

function createSupabaseClient() {
  const { url, publishableKey } = getSupabaseEnv();

  if (!url || !publishableKey) {
    console.warn("[Supabase] Chaves ausentes. Usando modo local de fallback para autenticação administrativa.");
    return createFallbackClient();
  }

  return createClient<Database>(url, publishableKey, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
