// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { getSupabaseEnv } from "./env";

const FALLBACK_SESSION_KEY = "rotamais-local-session";

function readFallbackSession() {
  if (typeof window === "undefined") return null;
  try {
    const raw = window.localStorage.getItem(FALLBACK_SESSION_KEY);
    return raw ? JSON.parse(raw) : null;
  } catch {
    return null;
  }
}

function writeFallbackSession(user: { id: string; email: string; full_name?: string } | null) {
  if (typeof window === "undefined") return;
  if (!user) {
    window.localStorage.removeItem(FALLBACK_SESSION_KEY);
    return;
  }
  window.localStorage.setItem(FALLBACK_SESSION_KEY, JSON.stringify(user));
}

function createFallbackClient() {
  return {
    auth: {
      async getSession() {
        const user = readFallbackSession();
        return {
          data: {
            session: user ? { access_token: "local-fallback-token", user } : null,
          },
          error: null,
        };
      },
      async getUser() {
        const user = readFallbackSession();
        return {
          data: {
            user: user
              ? { id: user.id, email: user.email, user_metadata: { full_name: user.full_name } }
              : null,
          },
          error: null,
        };
      },
      async signUp({ email, options }: { email: string; password: string; options?: { data?: Record<string, any> } }) {
        const id = crypto.randomUUID?.() ?? "local-" + Date.now();
        const user = { id, email, full_name: options?.data?.full_name ?? email };
        writeFallbackSession(user);
        return {
          data: {
            user: { id: user.id, email: user.email, user_metadata: { full_name: user.full_name } },
            session: { access_token: "local-fallback-token", user: { id: user.id, email: user.email } },
          },
          error: null,
        };
      },
      async signInWithPassword({ email }: { email: string; password: string }) {
        const user = readFallbackSession() ?? { id: "local-" + Date.now(), email, full_name: email };
        writeFallbackSession(user);
        return {
          data: {
            user: { id: user.id, email: user.email, user_metadata: { full_name: user.full_name } },
            session: { access_token: "local-fallback-token", user: { id: user.id, email: user.email } },
          },
          error: null,
        };
      },
      async signOut() {
        writeFallbackSession(null);
        return { error: null };
      },
      async getClaims() {
        const user = readFallbackSession();
        return {
          data: {
            claims: user ? { sub: user.id, email: user.email, user_metadata: { full_name: user.full_name } } : null,
          },
          error: null,
        };
      },
      onAuthStateChange() {
        return { data: { subscription: { unsubscribe() {} } } };
      },
      refreshSession() {
        return Promise.resolve({ data: { session: null }, error: null });
      },
      setSession() {
        return Promise.resolve({ data: { session: null }, error: null });
      },
    },
  } as any;
}

function createSupabaseClient() {
  const { url, publishableKey } = getSupabaseEnv();

  if (!url || !publishableKey) {
    console.warn("[Supabase] Chaves ausentes. Usando modo local de fallback para autenticação administrativa.");
    return createFallbackClient();
  }

  return createClient<Database>(url, publishableKey, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Fallback: lê o access_token diretamente do localStorage caso getSession() retorne null.
// O Supabase armazena a sessão em chaves no formato "sb-<project_ref>-auth-token".
export function getSupabaseSessionFromStorage(): string | undefined {
  if (typeof window === "undefined") return;
  try {
    for (let i = 0; i < window.localStorage.length; i++) {
      const key = window.localStorage.key(i);
      if (key?.startsWith("sb-") && key.endsWith("-auth-token")) {
        const raw = window.localStorage.getItem(key);
        if (!raw) continue;
        const parsed = JSON.parse(raw);
        const token = parsed?.access_token;
        if (token && typeof token === "string") return token;
      }
    }
  } catch {
    // ignore
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
